In [3]:
import torch
n= 5
x = torch.zeros((1,n))
torch.cat([x, x], dim=1).size(1)

10

In [6]:
import torch.nn as nn
import torch.nn.functional as F
x
x = torch.Tensor
F.relu([1,2])

TypeError: relu(): argument 'input' (position 1) must be Tensor, not list

In [59]:
torch.manual_seed(99)
import numpy as np 
w = torch.empty((3,3)).uniform_(-1,1)
x = torch.rand(3,1)
x = x.type_as(w)
y = torch.matmul(w,x)
display(y)
display(torch.relu(y))

tensor([[ 0.5433],
        [ 0.3598],
        [-0.3605]])

tensor([[0.5433],
        [0.3598],
        [0.0000]])

In [44]:
w.type()

'torch.LongTensor'

In [60]:
5//2

2

In [67]:
# torch.bmm()
display(torch.zeros((3,4)).unsqueeze(-1))
# display(torch.zeros((3,4)).size())

tensor([[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]])

In [77]:
from functools import partial 
basetwo = partial(int, baseeeeeeeeeeeeee=2)
basetwo('10010')


TypeError: 'baseeeeeeeeeeeeee' is an invalid keyword argument for int()

In [115]:
class parentClass(object):
    def __init__(self,input):
        self.input = input
        print('__Init__')
    def __call__(self, later,power):
        out = self.input ** power
        self.later = later
        print(self.input)
        print(out)
        print("__call__")
#         return out
    
# parentclass = parentClass(2)
# call = parentClass()
# parentclass()
parentclass(power=3)


TypeError: __call__() missing 1 required positional argument: 'later'

In [116]:
ls_x = "hi" is not None
x # do something if ls_x else do other things 

True

In [ ]:
if "hi" is not None:
    #do something with x
else: 
#     do other thing with x


In [73]:
basetwo.keywords

{'base': 2}